JWT_ADMIN_SECRET = process.env.JWT_ADMIN_SECRET
JWT_USER_SECRET = process.env.JWT_USER_SECRET
MONGO_DB_STRING = process.env.MONGO_DB_STRING

module.exports = {
    JWT_ADMIN_SECRET: JWT_ADMIN_SECRET,
    JWT_USER_SECRET: JWT_USER_SECRET,
    MONGO_DB_STRING: MONGO_DB_STRING
}